swagger:
  title: "Java Spring Framework"
  description: "Java Spring Framework"
  contact:
    name: "Byron Villegas Moya"
    url: ""
    email: "byronvillegasm@gmail.com"
  license: "MIT"
  licenseUrl: ""
  version: "1.0.0"
  basePackage: "cl.springframework"

server:
  servlet:
    context-path: "/api"
  port: 8080

spring:
  application:
    name: springframework-${swagger.version}
  profiles:
    active: default
  mvc:
    log-request-details: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: false
    content-type: text/html

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics

info:
  application:
    name: Java Spring Framework
    description: Java Spring Framework
    version: 1.0.0

security:
  whiteListUrls:
    - "/configuration/ui"
    - "/configuration/security"
    - "/v2/api-docs"
    - "/swagger-resources/**"
    - "/swagger-ui.html"
    - "/webjars/**"
    - "/actuator/**"
    - "/oauth/token"
  cors:
    allowCredentials: true
    allowedOrigin: "*"
    allowedHeader: "*"
    AllowedMethod: "*"
    basePath: "/**"

authorizacion:
  oauth:
    roles:
      usuario: "ROLE_USER"
      administrador: "ROLE_ADMINISTRATOR"

jwt:
  secret: "Jwt@Secret123"
  duration: 60

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] [%logger{36}] - %msg%n"
  level:
    org:
      springframework:
        web: INFO
    web: INFO